whiteboard/views/academics.py
from flask import Blueprint, flash, redirect, render_template, url_for
from whiteboard import settings as wbs
from whiteboard.forms import CourseForm, DepartmentForm, MajorForm, TermForm
from whiteboard.models import Course, Department, Major, Term, db
from whiteboard.views import admin_required
from whiteboard.views.exceptions import EntityNotFound

academics = Blueprint('academics', __name__, template_folder='../templates/academics', url_prefix='/academics')


@academics.route('/')
def index():
    departments = Department.query.all()
    majors = Major.query.all()
    courses = Course.query.all()
    terms = Term.query.all()
    return render_template('academics.html', departments=departments, majors=majors, courses=courses, terms=terms)


@academics.route('/departments/new', methods=['GET', 'POST'])
@admin_required
def new_department():
    form = DepartmentForm()

    if form.validate_on_submit():
        candidate = Department.query.filter(Department.name.ilike(form.name.data)).first()

        if candidate:
            flash('A department with that name already exists.', 'error')
        else:
            department = Department()
            form.populate_obj(department)
            db.session.add(department)
            db.session.commit()
            flash(f'{department} has been created.', 'success')
            return redirect(url_for('academics.index'))

    return render_template('edit-form.html', title='Departments', card_title='New Department', form=form)


@academics.route('/departments/edit/<department_id>', methods=['GET', 'POST'])
@admin_required
def edit_department(department_id):
    department = Department.query.filter_by(id=department_id).first()

    if not department:
        raise EntityNotFound(entity_name=Department.__name__, entity_id=department_id)

    form = DepartmentForm(obj=department)

    if form.validate_on_submit():
        candidate = Department.query.filter(Department.name.ilike(form.name.data)).first()

        if candidate and candidate != department:
            flash('A department with that name already exists.')
        else:
            form.populate_obj(department)
            db.session.commit()
            flash(f'Changes to department #{department.id} have been made.', 'success')

    return render_template('edit-form.html', title='Departments', card_title=f'Editing Department #{department.id}: {department}', form=form)


@academics.route('/majors/new', methods=['GET', 'POST'])
@admin_required
def new_major():
    form = MajorForm()

    if form.validate_on_submit():
        candidate = Major.query.filter(Major.name.ilike(form.name.data)).first()

        if candidate:
            flash('A department with that name already exists.', 'error')
        else:
            major = Major()
            form.populate_obj(major)
            db.session.add(major)
            db.session.commit()
            flash(f'{major} has been created.', 'success')
            return redirect(url_for('academics.index'))

    return render_template('edit-form.html', title='Majors', card_title='New Major', form=form)


@academics.route('/majors/edit/<major_id>', methods=['GET', 'POST'])
@admin_required
def edit_major(major_id):
    major = Major.query.filter_by(id=major_id).first()

    if not major:
        raise EntityNotFound(entity_name=Major.__name__, entity_id=major_id)

    form = MajorForm(obj=major)

    if form.validate_on_submit():
        candidate = Major.query.filter(Major.name.ilike(form.name.data)).first()

        if candidate and candidate != major:
            flash('A major with that name already exists.')
        else:
            form.populate_obj(major)
            db.session.commit()
            flash(f'Changes to major #{major.id} have been made.', 'success')

    return render_template('edit-form.html', title='Majors', card_title=f'Editing Major #{major.id}: {major}', form=form)


@academics.route('/courses/new', methods=['GET', 'POST'])
@admin_required
def new_course():
    if Department.query.count() < 1:
        flash('Please add a department first before adding a course.')
        return redirect(url_for('academics.index'))

    form = CourseForm()

    if form.validate_on_submit():
        candidate = Course.query.filter_by(department_id=form.department.data.id, code=form.code.data).first()

        if candidate:
            flash('A course with that code already exists.', 'error')
        else:
            course = Course()
            form.populate_obj(course)
            db.session.add(course)
            db.session.commit()
            flash(f'{course} has been created.', 'success')
            return redirect(url_for('academics.index'))

    return render_template('edit-form.html', title='Courses', card_title='New Course', form=form)


@academics.route('/courses/edit/<course_id>', methods=['GET', 'POST'])
@admin_required
def edit_course(course_id):
    course = Course.query.filter_by(id=course_id).first()

    if not course:
        raise EntityNotFound(entity_name=Course.__name__, entity_id=course_id)

    form = CourseForm(obj=course)

    if form.validate_on_submit():
        candidate = Course.query.filter_by(department_id=form.department.data.id, code=form.code.data).first()

        if candidate and candidate != course:
            flash('A course with that code already exists.')
        else:
            form.populate_obj(course)
            db.session.commit()
            flash(f'Changes to course #{course.id} have been made.', 'success')

    return render_template('edit-form.html', title='Courses', card_title=f'Editing Course #{course.id}: {course}', form=form)


@academics.route('/terms/new', methods=['GET', 'POST'])
@admin_required
def new_term():
    form = TermForm()

    if form.validate_on_submit():
        candidate = Term.query.filter((Term.start_date <= form.end_date.data) & (Term.end_date >= form.start_date.data)).first()

        if candidate:
            flash(f'A {wbs.ACADEMIC_TERM.system} within that date range already exists.', 'error')
        else:
            term = Term()
            form.populate_obj(term)
            db.session.add(term)
            db.session.commit()
            flash(f'{term} has been created.', 'success')
            return redirect(url_for('academics.index'))

    return render_template('edit-form.html', title=wbs.ACADEMIC_TERM.system_plural_capital, card_title=f'New {wbs.ACADEMIC_TERM.system_capital}', form=form)


@academics.route('/terms/edit/<term_id>', methods=['GET', 'POST'])
@admin_required
def edit_term(term_id):
    term = Term.query.filter_by(id=term_id).first()

    if not term:
        raise EntityNotFound(entity_name=wbs.ACADEMIC_TERM.system_capital, entity_id=term_id)

    form = TermForm(obj=term)

    if form.validate_on_submit():
        candidate = Term.query.filter((Term.start_date <= form.end_date.data) & (Term.end_date >= form.start_date.data)).first()

        if candidate and candidate != term:
            flash(f'A {wbs.ACADEMIC_TERM.system} within that date range already exists.')
        else:
            form.populate_obj(term)
            db.session.commit()
            flash(f'Changes to {wbs.ACADEMIC_TERM.system} #{term.id} have been made.', 'success')

    return render_template('edit-form.html', title=wbs.ACADEMIC_TERM.system_plural_capital, card_title=f'Editing {wbs.ACADEMIC_TERM.system_capital} #{term.id}: {term}', form=form)

whiteboard/views/admin.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user
from whiteboard.forms import DepartmentForm, MajorForm, CourseForm, TermForm, ClassForm
from whiteboard.models import db, User, Department, Major, Course, Term, Class
from whiteboard import settings as wbs

admin = Blueprint('admin', __name__, template_folder='../templates/admin')


@admin.before_request
@login_required
def admin_required():
    if not current_user.is_teacher:
        abort(403)


@admin.route('/applicants', methods=['GET', 'POST'])
def applicants():
    applicants = User.query.filter_by(join_date=None)
    return render_template('applicants.html', applicants=applicants)


@admin.route('/applicants/<applicant_id>', methods=['POST'])
def admissions(applicant_id):
    applicant = User.query.filter_by(id=applicant_id).first()

    if not applicant or applicant.is_active:
        flash('This applicant does not exist.', 'error')
        return redirect(url_for('admin.applicants'))

    if 'decision' in request.form:
        pass
    elif 'confirmation' in request.form:
        if request.form['confirmation'] == 'Accept':
            applicant.join_date = datetime.utcnow()
            db.session.commit()
            flash(f"{applicant.full_name}'s account with {wbs.CAMPUS_CARD.formal_name} {applicant.username} has been verified.", 'success')
        elif request.form['confirmation'] == 'Reject':
            db.session.delete(applicant)
            db.session.commit()
            flash(f"{applicant.full_name}'s application with {wbs.CAMPUS_CARD.formal_name} {applicant.username} has been deleted.", 'success')

        return redirect(url_for('admin.applicants'))
    else:
        flash('An unknown error has occurred', 'error')
        return redirect(url_for('admin.applicants'))

    return render_template('admissions.html', applicant=applicant)


@admin.route('/academics/departments/new', methods=['GET', 'POST'])
def new_department():
    form = DepartmentForm()

    if form.validate_on_submit():
        candidate = Department.query.filter(Department.name.ilike(form.name.data)).first()

        if candidate:
            flash('A department with that name already exists.', 'error')
        else:
            department = Department()
            form.populate_obj(department)
            db.session.add(department)
            db.session.commit()
            flash(f'{department} has been created.', 'success')
            return redirect(url_for('root.academics'))

    return render_template('division.html', title='Departments', card_title='New Department', form=form)


@admin.route('/academics/departments/edit/<department_id>', methods=['GET', 'POST'])
def edit_department(department_id):
    department = Department.query.filter_by(id=department_id).first()

    if not department:
        flash('This department does not exist.', 'error')
        return redirect(url_for('root.academics'))

    form = DepartmentForm(obj=department)

    if form.validate_on_submit():
        candidate = Department.query.filter(Department.name.ilike(form.name.data)).first()

        if candidate and candidate != department:
            flash('A department with that name already exists.')
        else:
            form.populate_obj(department)
            db.session.commit()
            flash(f'Changes to department #{department.id} have been made.', 'success')

    return render_template('division.html', title='Departments', card_title=f'Editing Department #{department.id}: {department}', form=form)


@admin.route('/academics/majors/new', methods=['GET', 'POST'])
def new_major():
    form = MajorForm()

    if form.validate_on_submit():
        candidate = Major.query.filter(Major.name.ilike(form.name.data)).first()

        if candidate:
            flash('A department with that name already exists.', 'error')
        else:
            major = Major()
            form.populate_obj(major)
            db.session.add(major)
            db.session.commit()
            flash(f'{major} has been created.', 'success')
            return redirect(url_for('root.academics'))

    return render_template('division.html', title='Majors', card_title='New Major', form=form)


@admin.route('/academics/majors/edit/<major_id>', methods=['GET', 'POST'])
def edit_major(major_id):
    major = Major.query.filter_by(id=major_id).first()

    if not major:
        flash('This major does not exist.', 'error')
        return redirect(url_for('root.academics'))

    form = MajorForm(obj=major)

    if form.validate_on_submit():
        candidate = Major.query.filter(Major.name.ilike(form.name.data)).first()

        if candidate and candidate != major:
            flash('A major with that name already exists.')
        else:
            form.populate_obj(major)
            db.session.commit()
            flash(f'Changes to major #{major.id} have been made.', 'success')

    return render_template('division.html', title='Majors', card_title=f'Editing Major #{major.id}: {major}', form=form)


@admin.route('/academics/courses/new', methods=['GET', 'POST'])
def new_course():
    if Department.query.count() < 1:
        flash('Please add a department first before adding a course.')
        return redirect(url_for('root.academics'))

    form = CourseForm()

    if form.validate_on_submit():
        candidate = Course.query.filter_by(department_id=form.department.data.id, code=form.code.data).first()

        if candidate:
            flash('A course with that code already exists.', 'error')
        else:
            course = Course()
            form.populate_obj(course)
            db.session.add(course)
            db.session.commit()
            flash(f'{course} has been created.', 'success')
            return redirect(url_for('root.academics'))

    return render_template('division.html', title='Courses', card_title='New Course', form=form)


@admin.route('/academics/courses/edit/<course_id>', methods=['GET', 'POST'])
def edit_course(course_id):
    course = Course.query.filter_by(id=course_id).first()

    if not course:
        flash('This course does not exist.', 'error')
        return redirect(url_for('root.academics'))

    form = CourseForm(obj=course)

    if form.validate_on_submit():
        candidate = Course.query.filter_by(department_id=form.department.data.id, code=form.code.data).first()

        if candidate and candidate != course:
            flash('A course with that code already exists.')
        else:
            form.populate_obj(course)
            db.session.commit()
            flash(f'Changes to course #{course.id} have been made.', 'success')

    return render_template('division.html', title='Courses', card_title=f'Editing Course #{course.id}: {course}', form=form)


@admin.route('/terms/new', methods=['GET', 'POST'])
def new_term():
    form = TermForm()

    if form.validate_on_submit():
        candidate = Term.query.filter((Term.start_date <= form.end_date.data) & (Term.end_date >= form.start_date.data)).first()

        if candidate:
            flash(f'A {wbs.ACADEMIC_TERM.system} within that date range already exists.', 'error')
        else:
            term = Term()
            form.populate_obj(term)
            db.session.add(term)
            db.session.commit()
            flash(f'{term} has been created.', 'success')
            return redirect(url_for('root.academics'))

    return render_template('division.html', title=wbs.ACADEMIC_TERM.system_plural_capital, card_title=f'New {wbs.ACADEMIC_TERM.system_capital}', form=form)


@admin.route('/terms/edit/<term_id>', methods=['GET', 'POST'])
def edit_term(term_id):
    term = Term.query.filter_by(id=term_id).first()

    if not term:
        flash(f'This {wbs.ACADEMIC_TERM.system} does not exist.', 'error')
        return redirect(url_for('root.academics'))

    form = TermForm(obj=term)

    if form.validate_on_submit():
        candidate = Term.query.filter((Term.start_date <= form.end_date.data) & (Term.end_date >= form.start_date.data)).first()

        if candidate and candidate != term:
            flash(f'A {wbs.ACADEMIC_TERM.system} within that date range already exists.')
        else:
            form.populate_obj(term)
            db.session.commit()
            flash(f'Changes to {wbs.ACADEMIC_TERM.system} #{term.id} have been made.', 'success')

    return render_template('division.html', title=wbs.ACADEMIC_TERM.system_plural_capital, card_title=f'Editing {wbs.ACADEMIC_TERM.system_capital} #{term.id}: {term}', form=form)


@admin.route('/classes/new', methods=['GET', 'POST'])
def new_class():
    prereqs = []

    if Course.query.count() < 1:
        prereqs.append('course')

    if Term.query.count() < 1:
        prereqs.append(wbs.ACADEMIC_TERM.system)

    if prereqs:
        flash(f"Please add a {', '.join(prereqs)} first before adding a class.")
        return redirect(url_for('root.classes'))

    form = ClassForm()

    if form.validate_on_submit():
        candidate = Class.query.filter_by(term_id=form.term.data.id, course_id=form.course.data.id, section=form.section.data).first()

        if candidate:
            flash(f'A class with that {wbs.ACADEMIC_TERM.system}, course, and section already exists.', 'error')
        else:
            class_ = Class()
            form.populate_obj(class_)
            class_.teacher_id = current_user.id
            db.session.add(class_)
            db.session.commit()
            flash(f'{class_} has been created.', 'success')
            return redirect(url_for('root.classes'))

    return render_template('division.html', title='Classes', card_title='New Class', back_url='root.classes', form=form)


@admin.route('/classes/edit/<class_id>', methods=['GET', 'POST'])
def edit_class(class_id):
    class_ = Class.query.filter_by(id=class_id).first()

    if not class_:
        flash('This class does not exist.', 'error')

whiteboard/views/root.py
from flask import Blueprint, render_template

root = Blueprint('root', __name__, template_folder='../templates/root')


@root.route('/')
@root.route('/index')
def index():
    return render_template('index.html')

whiteboard/templates/root/academics.html
{% extends 'layout.html' %}

{% from 'macros.html' import action_links, print_class_info with context %}

{% block title %}Academics - {{ super() }}{% endblock %}

{% block content %}
    <nav>
        <header><h2>Index</h2></header>
        <ul>
            <li><a href="#departments">Departments</a></li>
            <li><a href="#majors">Majors</a></li>
            <li><a href="#majors">Courses</a></li>
            <li><a href="#terms">{{ config.ACADEMIC_TERM.system_plural_capital }}</a></li>
        </ul>
    </nav>
    <section id="departments">
        <header><h2>Departments</h2></header>
        {% call action_links('h3', current_user.is_teacher) %}
            {{ nav_link(url_for('admin.new_department'), 'Add New Department') }}
        {% endcall %}
        {% if departments %}
            {% for department in departments %}
                <section class="card">
                    <header><h3>{{ department }}</header></h3>
                    <p>Chair: <strong class="emphasized">{{ department.chair }}</strong></p>
                    <p>Office: <strong class="emphasized">{{ department.office }}</strong></p>
                    {% call action_links('h4', current_user.is_teacher) %}
                        {{ nav_link(url_for('admin.edit_department', department_id=department.id), 'Edit') }}
                    {% endcall %}
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No departments listed.</em></p>
        {% endif %}
    </section>
    <section id="majors">
        <header><h2>Majors</h2></header>
        {% call action_links('h3', current_user.is_teacher) %}
            {{ nav_link(url_for('admin.new_major'), 'Add New Major') }}
        {% endcall %}
        {% if majors %}
            {% for major in majors %}
                <section class="card">
                    <header><h3>{{ major }}</header></h3>
                    {% if major.department %}
                        <p>Department: <strong class="emphasized">{{ major.department.name }}</strong></p>
                    {% endif %}
                    {% call action_links('h4', current_user.is_teacher) %}
                        {{ nav_link(url_for('admin.edit_major', major_id=major.id), 'Edit') }}
                    {% endcall %}
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No majors listed.</em></p>
        {% endif %}
    </section>
    <section id="courses">
        <header><h2>Courses</h2></header>
        {% call action_links('h3', current_user.is_teacher) %}
            {{ nav_link(url_for('admin.new_course'), 'Add New Course') }}
        {% endcall %}
        {% if courses %}
            {% for course in courses %}
                <section class="card">
                    <header><h3>{{ course }}</header></h3>
                    <p>Name: <strong class="emphasized">{{ course.name }}</strong></p>
                    {% call action_links('h4', current_user.is_teacher) %}
                        {{ nav_link(url_for('admin.edit_course', course_id=course.id), 'Edit') }}
                    {% endcall %}
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No courses listed.</em></p>
        {% endif %}
    </section>
    <section id="terms">
        <header><h2>{{ config.ACADEMIC_TERM.system_plural_capital }}</h2></header>
        {% call action_links('h3', current_user.is_teacher) %}
            {{ nav_link(url_for('admin.new_term'), 'Add New ' + config.ACADEMIC_TERM.system_capital) }}
        {% endcall %}
        {% if terms %}
            {% for term in terms %}
                <section class="card">
                    <header><h3>{{ term }}</header></h3>
                    <p>Start Date: <strong class="emphasized">{{ term.start_date }}</strong></p>
                    <p>End Date: <strong class="emphasized">{{ term.end_date }}</strong></p>
                    {% call action_links('h4', current_user.is_teacher) %}
                        {{ nav_link(url_for('admin.edit_term', term_id=term.id), 'Edit') }}
                    {% endcall %}
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No {{ config.ACADEMIC_TERM.system_plural }} listed.</em></p>
        {% endif %}
    </section>
{% endblock %}

whiteboard/templates/root/class.html
{% extends 'classes.html' %}

{% from 'macros.html' import print_user with context %}

{% block title %}{{ current_class }} - {{ super() }}{% endblock %}

{% block style %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='users.css') }}">
{% endblock %}

{% block content %}
    <section>
        <header><h2>{{ current_class }}</h2></header>
        {{ print_class_info(current_class) }}
        <section>
            <header><h3>Students</h3></header>
            {% if current_user.is_teacher %}
                <section class="card">
                    <header><h4>Registration</h4></header>
                    <form class="inlined" action="" method="post">
                        <div>
                            {{ get_csrf_token() }}
                            {{ form.student.label }}
                            {{ form.student }}
                        </div>
                        <div>
                            <input type="submit" name="action" value="Enroll Student">
                            <input type="submit" name="action" value="Withdraw Student">
                        </div>
                    </form>
                </section>
            {% endif %}
            {% if students.count() > 0 %}
                <ul class="users-list">
                    {% for student in students %}
                        {% if current_class.teacher.user == current_user %}
                            {% call print_user(student.user) %}
                                <form class="inlined" action="{{ url_for('admin.mark_attendance', class_id=current_class.id) }}" method="post">
                                    {{ get_csrf_token() }}
                                    <input type="submit" name="action" value="Mark Present">
                                </form>
                            {% endcall %}
                        {% else %}
                            {{ print_user(student.user) }}
                        {% endif %}
                    {% endfor %}
                </ul>
            {% else %}
                <p class="emphasized"><em>No students enrolled.</em></p>
            {% endif %}
        </section>
    </section>
{% endblock %}

whiteboard/templates/root/classes.html
{% extends 'forms.html' %}

{% from 'macros.html' import action_links, print_class_info, get_csrf_token with context %}

{% block title %}Classes - {{ super() }}{% endblock %}

{% block content %}
    <section>
        <header><h2>Classes</h2></header>
        {% call action_links('h3', current_user.is_teacher) %}
            {{ nav_link(url_for('admin.new_class'), 'Add New Class') }}
        {% endcall %}
        {% if classes %}
            {% for class in classes %}
                <section class="card">
                    <header><h3><a href="{{ url_for('root.class_info', class_id=class.id) }}">{{ class }}</a></header></h3>
                    {{ print_class_info(class) }}
                    {% call action_links('h4', current_user.is_teacher) %}
                        {{ nav_link(url_for('admin.edit_class', class_id=class.id), 'Edit') }}
                    {% endcall %}
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No classes listed.</em></p>
        {% endif %}
    </section>
{% endblock %}

whiteboard/templates/root/index.html
{% extends 'layout.html' %}

{% from 'macros.html' import get_user_classes, print_user_info with context %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
{% endblock %}

{% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/twitterFetcher_min.js') }}"></script>
    <script>
        function initialize() {
            var configProfile = {
                "profile": {"screenName": "{{ config.TWITTER_SCREEN_NAME or 'CityCollegeNY' }}"},
                "domId": "tweets",
                "maxTweets": 4,
                "enableLinks": true,
                "showUser": true,
                "showTime": true,
                "showImages": true,
                "lang": "en",
            };
            twitterFetcher.fetch(configProfile);
        }
    </script>
{% endblock %}

{% block body_attributes %}onload="initialize();"{% endblock %}

{% block content %}
    {% if current_user.is_authenticated %}
        <section>
            <header><h2>My Profile</h2></header>
            <section class="card">
                {{ print_user_info(current_user, 'h3') }}
            </section>
        </section>

        <section>
            <header><h2>My Classes</h2></header>
            {% if current_user.classes %}
                {{ get_user_classes(current_user) }}
            {% else %}
                <p class="emphasized"><em>You're not {{ 'teaching' if current_user.is_teacher else 'taking' }} any classes.</em></p>
            {% endif %}
        </section>
    {% else %}
        <section>
            <header><h2>Whiteboard</h2></header>
            <p><strong>Whiteboard</strong> is a web-based gradebook and attendance tracker for teachers and students.</p>
        </section>
    {% endif %}

    <section>
        <header><h2>Social Media</h2></header>
        <section id="twitter" class="card">
            <header><h3>Twitter</h3></header>
            <div id="tweets"></div>
        </section>
    </section>
{% endblock %}