whiteboard/views/classes.py
from datetime import datetime
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from whiteboard import settings as wbs
from whiteboard.forms import AbsenceForm, ClassForm, EnrollmentForm
from whiteboard.models import Absence, Class, Course, Enrollment, Student, Term, db
from whiteboard.views import admin_required
from whiteboard.views.exceptions import EntityNotFound

classes = Blueprint('classes', __name__, template_folder='../templates/classes', url_prefix='/classes')


def verify_class_exists(class_id):
    current_class = Class.query.filter_by(id=class_id).first()

    if not current_class:
        raise EntityNotFound(entity_name=Class.__name__, entity_id=class_id)

    return current_class


def verify_user_teaches_class(class_id):
    current_class = verify_class_exists(class_id)

    if current_class.teacher.user != current_user:
        abort(403, "You do not have permission to change another instructor's class.")

    return current_class


def get_student_info(class_id, student_id, date=datetime.utcnow().date()):
    verify_user_teaches_class(class_id)
    student_enrollment = Enrollment.query.filter_by(student_id=student_id, class_id=class_id).first()

    if not student_enrollment:
        abort(400)

    student_absence = Absence.query.filter_by(student_id=student_id, class_id=class_id, date=date).first()
    return student_enrollment, student_absence


@classes.route('/')
@login_required
def index():
    classes = Class.query.all()
    return render_template('classes.html', classes=classes)


@classes.route('/new', methods=['GET', 'POST'])
@admin_required
def new_class():
    prereqs = []

    if Course.query.count() < 1:
        prereqs.append('course')

    if Term.query.count() < 1:
        prereqs.append(wbs.ACADEMIC_TERM.system)

    if prereqs:
        flash(f"Please add a {', '.join(prereqs)} first before adding a class.")
        return redirect(url_for('classes.index'))

    form = ClassForm()

    if form.validate_on_submit():
        candidate = Class.query.filter_by(term_id=form.term.data.id, course_id=form.course.data.id).filter(Class.section.ilike(form.section.data)).first()

        if candidate:
            flash(f'A class with that {wbs.ACADEMIC_TERM.system}, course, and section already exists.', 'error')
        else:
            class_ = Class(teacher_id=current_user.id)
            form.populate_obj(class_)
            db.session.add(class_)
            db.session.commit()
            flash(f'{class_} has been created.', 'success')
            return redirect(url_for('classes.index'))

    return render_template('edit-form.html', title='Classes', card_title='New Class', form=form)


@classes.route('/edit/<class_id>', methods=['GET', 'POST'])
@admin_required
def edit_class(class_id):
    class_ = verify_user_teaches_class(class_id)
    form = ClassForm(obj=class_)

    if form.validate_on_submit():
        candidate = Class.query.filter_by(term_id=form.term.data.id, course_id=form.course.data.id).filter(Class.section.ilike(form.section.data)).first()

        if candidate and candidate != class_:
            flash(f'A class with that {wbs.ACADEMIC_TERM.system}, course, and section already exists.')
        else:
            form.populate_obj(class_)
            db.session.commit()
            flash(f'Changes to class #{class_.id} have been made.', 'success')

    return render_template('edit-form.html', title='Classes', card_title=f'Editing Class #{class_.id}: {class_}', form=form)


@classes.route('/<class_id>', methods=['GET', 'POST'])
@login_required
def class_info(class_id):
    current_class = verify_class_exists(class_id)
    students = Student.query.join(Enrollment).filter_by(class_id=class_id)
    return render_template('class-info.html', current_class=current_class, students=students)


@classes.route('/<class_id>/enrollment', methods=['GET', 'POST'])
@admin_required
def enrollment(class_id):
    current_class = verify_user_teaches_class(class_id)
    students = Student.query.join(Enrollment).filter_by(class_id=class_id)
    form = EnrollmentForm()

    if form.validate_on_submit():
        if request.method != 'POST' or not request.form['action']:
            abort(400)

        student = Student.query.filter_by(user_id=form.student.data.user_id).first()

        if student:
            student_enrollment = Enrollment.query.filter_by(student_id=student.user.id, class_id=class_id).first()

            if request.form['action'] == 'Enroll Student':
                if student_enrollment:
                    flash('This student is already enrolled in this class.')
                else:
                    enrollment = Enrollment(student_id=student.user.id, class_id=class_id)
                    db.session.add(enrollment)
                    db.session.commit()
                    flash(f'{student} has been enrolled in this class.', 'success')
            else:
                if student_enrollment:
                    db.session.delete(student_enrollment)
                    db.session.commit()
                    flash(f'{student} has been withdrawn from the class.', 'success')
                else:
                    flash("You cannot withdraw a student that has not been enrolled.")
        else:
            abort(400)

    return render_template('enrollment.html', current_class=current_class, students=students, form=form)


@classes.route('/<class_id>/absence/add/<date>/<student_id>', methods=['POST'])
@admin_required
def mark_absent(class_id, date, student_id):
    utcnow_date = datetime.utcnow().date() if date == 'today' else date
    student_enrollment, student_absence = get_student_info(class_id, student_id, utcnow_date)

    if utcnow_date < student_enrollment.class_.term.start_date:
        flash(f'Date of absence must be on or after the {wbs.ACADEMIC_TERM.system} start date.', 'error')
    elif utcnow_date > student_enrollment.class_.term.end_date:
        flash(f'Date of absence must be on or before the {wbs.ACADEMIC_TERM.system} end date.', 'error')
    else:
        if student_absence:
            flash(f'{student_enrollment.student} has already been marked absent.')
        else:
            absence = Absence(student_id=student_id, class_id=class_id, date=utcnow_date)
            db.session.add(absence)
            db.session.commit()
            flash(f'{student_enrollment.student} has been marked absent.', 'success')

    return redirect(url_for('classes.class_info', class_id=class_id))


@classes.route('/<class_id>/absence/remove/<date>/<student_id>', methods=['POST'])
@admin_required
def remove_absence(class_id, date, student_id):
    if date == 'today':
        student_enrollment, student_absence = get_student_info(class_id, student_id)
    else:
        student_enrollment, student_absence = get_student_info(class_id, student_id, date)

    if student_absence:
        db.session.delete(student_absence)
        db.session.commit()
        flash(f"{student_enrollment.student}'s absence has been removed.", 'success')
    else:
        flash(f"{student_enrollment.student}'s absence has already been removed.")

    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(url_for('classes.class_info', class_id=class_id))


@classes.route('/<class_id>/absences/', methods=['GET', 'POST'])
@login_required
def absence_log(class_id):
    current_class = verify_class_exists(class_id)

    if not current_class.has_user(current_user):
        abort(403)

    if current_user.is_teacher:
        absences = Absence.query.filter_by(class_id=class_id).order_by(Absence.date.desc())
    else:
        absences = Absence.query.filter_by(class_id=class_id, student_id=current_user.id).order_by(Absence.date.desc())

    return render_template('absence-log.html', current_class=current_class, absences=absences)


@classes.route('/<class_id>/absences/record', methods=['GET', 'POST'])
@admin_required
def record_absence(class_id):
    current_class = verify_class_exists(class_id)
    absences = Absence.query.filter_by(class_id=class_id).order_by(Absence.date.desc())
    form = AbsenceForm()
    form.student.query = Student.query.join(Enrollment).filter_by(class_id=class_id)

    if form.validate_on_submit():
        # Do not use the template returned by `mark_absent`
        mark_absent(class_id=class_id, date=form.date.data, student_id=form.student.data.user.id)

    return render_template('record-absence.html', current_class=current_class, absences=absences, form=form)

whiteboard/templates/classes/absence-log.html
{% extends 'class-info.html' %}

{% block title %}Absence Log - {{ super() }}{% endblock %}

{% block subcontent %}
    <section>
        <header>
            <h3>Absence Log</h3>
            {% call action_links(current_class.teacher == current_user.teacher) %}
                {% block record_toggler %}
                    {{ nav_link(url_for('classes.record_absence', class_id=current_class.id), 'Enter Manual Mode') }}
                {% endblock %}
            {% endcall %}
        </header>

        {% block log_content %}{% endblock %}

        {% if absences.count() > 0 %}
            {% set ns = namespace(prev_date=none) %}
            {% for absence in absences %}
                {% if ns.prev_date is none or absence.date != ns.prev_date%}
                    {% if ns.prev_date is not none %}
                        </ul>
                    </section>
                    {% endif %}
                    <section>
                        <header><h4>{{ absence.date }}</h4></header>
                        <ul class="user-list">
                            {# Closing tags above #}
                {% endif %}

                {% call print_user(absence.student.user) %}
                    <ul>
                        <li class="emphasized">Absences: <strong>{{ absence.student.absences|length }}</strong></li>
                        {% if current_class.teacher == current_user.teacher %}
                            <li>
                                <form class="inlined" action="{{ url_for('classes.remove_absence', class_id=absence.class_id, date=absence.date, student_id=absence.student_id) }}" method="post">
                                    {{ get_csrf_token() }}
                                    <input type="submit" name="action" value="Remove Absence">
                                </form>
                            </li>
                        {% endif %}
                    </ul>
                {% endcall %}

                {% set ns.prev_date = absence.date %}
            {% endfor %}
                            {# Closing tags for last absence in absences #}
                        </ul>
                    </section>
        {% else %}
            <p class="emphasized">
                <em>
                    {% if current_user.is_teacher %}
                        No student was absent so far.
                    {% else %}
                        You don't have any absences.
                    {% endif %}
                </em>
            </p>
        {% endif %}
    </section>
{% endblock %}

whiteboard/templates/classes/class-info.html
{% extends 'classes.html' %}

{% from 'macros.html' import print_class_info, print_class_links, print_user with context %}

{% block title %}{{ current_class }} - {{ super() }}{% endblock %}

{% block style %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='users.css') }}">
{% endblock %}

{% block content %}
    <section>
        <header>
            <h2>{{ current_class }}</h2>
            {{ print_class_links(current_class, False) }}
        </header>

        <section class="card">
            <header>
                <h3>Class Information</h3>
                {% call action_links(current_class.teacher == current_user.teacher) %}
                    {{ nav_link(url_for('classes.edit_class', class_id=current_class.id), 'Edit', append_return_url=True) }}
                {% endcall %}
            </header>
            {{ print_class_info(current_class) }}
        </section>

        {% block subcontent %}
            <section>
                <header>
                    <h3>Students</h3>
                    {% call action_links(current_class.has_user(current_user)) %}
                        {% block enrollment_toggler %}
                            {{ nav_link(url_for('classes.enrollment', class_id=current_class.id), 'Show Enrollment Panel', current_class.teacher == current_user.teacher) }}
                        {% endblock %}
                    {% endcall %}
                </header>

                {% block enrollment_content %}{% endblock %}

                {% if students.count() > 0 %}
                    <ul class="user-list">
                        {% for student in students %}
                            {% if current_class.has_user(current_user) and student.absent(current_class.id) %}
                                {% set print_user_class = 'absent' %}
                            {% else %}
                                {% set print_user_class = '' %}
                            {% endif %}

                            {% if current_class.teacher.user == current_user %}
                                {% call print_user(student.user, class=print_user_class) %}
                                    <form class="inlined" method="post">
                                        {{ get_csrf_token() }}
                                        {% if student.absent(current_class.id) %}
                                            <input type="submit" name="action" value="Remove Absence" formaction="{{ url_for('classes.remove_absence', class_id=current_class.id, date='today', student_id=student.user_id) }}">
                                        {% else %}
                                            <input type="submit" name="action" value="Mark Absent" formaction="{{ url_for('classes.mark_absent', class_id=current_class.id, date='today', student_id=student.user_id) }}">
                                        {% endif %}
                                    </form>
                                {% endcall %}
                            {% else %}
                                {{ print_user(student.user, class=print_user_class) }}
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% else %}
                    <p class="emphasized"><em>No students enrolled.</em></p>
                {% endif %}
            </section>
        {% endblock %}
    </section>
{% endblock %}

whiteboard/templates/classes/classes.html
{% extends 'forms.html' %}

{% from 'macros.html' import action_links, print_class_card, get_csrf_token with context %}

{% block title %}Classes - {{ super() }}{% endblock %}

{% block content %}
    <section>
        <header>
            <h2>Classes</h2>
            {% call action_links(current_user.is_teacher) %}
                {{ nav_link(url_for('classes.new_class'), 'Add New Class', append_return_url=True) }}
            {% endcall %}
        </header>
        {% if classes %}
            {% for class in classes %}
                {{ print_class_card(class, actions_print_condition=class.has_user(current_user)) }}
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No classes listed.</em></p>
        {% endif %}
    </section>
{% endblock %}

whiteboard/templates/classes/enrollment.html
{% extends 'class-info.html' %}

{% block title %}Enrollment - {{ super() }}{% endblock %}

{% block enrollment_toggler %}
    {{ nav_link(url_for('classes.class_info', class_id=current_class.id), 'Hide Enrollment Panel') }}
{% endblock %}

{% block enrollment_content %}
    <section>
        <header><h4>Enrollment</h4></header>
        <form class="inlined" method="post">
            <div>
                {{ get_csrf_token() }}
                {{ form.student.label }}
                {{ form.student }}
            </div>

            <div>
                <input type="submit" name="action" value="Enroll Student">
                <input type="submit" name="action" value="Withdraw Student">
            </div>
        </form>
    </section>
    {{ super() }}
{% endblock %}

whiteboard/templates/classes/record-absence.html
{% extends 'absence-log.html' %}

{% block title %}Record Absence - {{ super() }}{% endblock %}

{% block record_toggler %}
    {{ nav_link(url_for('classes.absence_log', class_id=current_class.id), 'Exit Manual Mode') }}
{% endblock %}

{% block log_content %}
    {{ print_form(form=form, method='post') }}
{% endblock %}