whiteboard/views/academics.py
from flask import Blueprint, flash, redirect, render_template, url_for
from whiteboard import settings as wbs
from whiteboard.forms import CourseForm, DepartmentForm, MajorForm, TermForm
from whiteboard.models import Course, Department, Major, Term, db
from whiteboard.views import admin_required
from whiteboard.views.exceptions import EntityNotFound

academics = Blueprint('academics', __name__, template_folder='../templates/academics', url_prefix='/academics')


@academics.route('/')
def index():
    departments = Department.query.all()
    majors = Major.query.all()
    courses = Course.query.all()
    terms = Term.query.all()
    return render_template('academics.html', departments=departments, majors=majors, courses=courses, terms=terms)


@academics.route('/departments/new', methods=['GET', 'POST'])
@admin_required
def new_department():
    form = DepartmentForm()

    if form.validate_on_submit():
        candidate = Department.query.filter(Department.name.ilike(form.name.data)).first()

        if candidate:
            flash('A department with that name already exists.', 'error')
        else:
            department = Department()
            form.populate_obj(department)
            db.session.add(department)
            db.session.commit()
            flash(f'{department} has been created.', 'success')
            return redirect(url_for('academics.index'))

    return render_template('edit-form.html', title='Departments', card_title='New Department', form=form)


@academics.route('/departments/edit/<department_id>', methods=['GET', 'POST'])
@admin_required
def edit_department(department_id):
    department = Department.query.filter_by(id=department_id).first()

    if not department:
        raise EntityNotFound(entity_name=Department.__name__, entity_id=department_id)

    form = DepartmentForm(obj=department)

    if form.validate_on_submit():
        candidate = Department.query.filter(Department.name.ilike(form.name.data)).first()

        if candidate and candidate != department:
            flash('A department with that name already exists.')
        else:
            form.populate_obj(department)
            db.session.commit()
            flash(f'Changes to department #{department.id} have been made.', 'success')

    return render_template('edit-form.html', title='Departments', card_title=f'Editing Department #{department.id}: {department}', form=form)


@academics.route('/majors/new', methods=['GET', 'POST'])
@admin_required
def new_major():
    form = MajorForm()

    if form.validate_on_submit():
        candidate = Major.query.filter(Major.name.ilike(form.name.data)).first()

        if candidate:
            flash('A department with that name already exists.', 'error')
        else:
            major = Major()
            form.populate_obj(major)
            db.session.add(major)
            db.session.commit()
            flash(f'{major} has been created.', 'success')
            return redirect(url_for('academics.index'))

    return render_template('edit-form.html', title='Majors', card_title='New Major', form=form)


@academics.route('/majors/edit/<major_id>', methods=['GET', 'POST'])
@admin_required
def edit_major(major_id):
    major = Major.query.filter_by(id=major_id).first()

    if not major:
        raise EntityNotFound(entity_name=Major.__name__, entity_id=major_id)

    form = MajorForm(obj=major)

    if form.validate_on_submit():
        candidate = Major.query.filter(Major.name.ilike(form.name.data)).first()

        if candidate and candidate != major:
            flash('A major with that name already exists.')
        else:
            form.populate_obj(major)
            db.session.commit()
            flash(f'Changes to major #{major.id} have been made.', 'success')

    return render_template('edit-form.html', title='Majors', card_title=f'Editing Major #{major.id}: {major}', form=form)


@academics.route('/courses/new', methods=['GET', 'POST'])
@admin_required
def new_course():
    if Department.query.count() < 1:
        flash('Please add a department first before adding a course.')
        return redirect(url_for('academics.index'))

    form = CourseForm()

    if form.validate_on_submit():
        candidate = Course.query.filter_by(department_id=form.department.data.id, code=form.code.data).first()

        if candidate:
            flash('A course with that code already exists.', 'error')
        else:
            course = Course()
            form.populate_obj(course)
            db.session.add(course)
            db.session.commit()
            flash(f'{course} has been created.', 'success')
            return redirect(url_for('academics.index'))

    return render_template('edit-form.html', title='Courses', card_title='New Course', form=form)


@academics.route('/courses/edit/<course_id>', methods=['GET', 'POST'])
@admin_required
def edit_course(course_id):
    course = Course.query.filter_by(id=course_id).first()

    if not course:
        raise EntityNotFound(entity_name=Course.__name__, entity_id=course_id)

    form = CourseForm(obj=course)

    if form.validate_on_submit():
        candidate = Course.query.filter_by(department_id=form.department.data.id, code=form.code.data).first()

        if candidate and candidate != course:
            flash('A course with that code already exists.')
        else:
            form.populate_obj(course)
            db.session.commit()
            flash(f'Changes to course #{course.id} have been made.', 'success')

    return render_template('edit-form.html', title='Courses', card_title=f'Editing Course #{course.id}: {course}', form=form)


@academics.route('/terms/new', methods=['GET', 'POST'])
@admin_required
def new_term():
    form = TermForm()

    if form.validate_on_submit():
        candidate = Term.query.filter((Term.start_date <= form.end_date.data) & (Term.end_date >= form.start_date.data)).first()

        if candidate:
            flash(f'A {wbs.ACADEMIC_TERM.system} within that date range already exists.', 'error')
        else:
            term = Term()
            form.populate_obj(term)
            db.session.add(term)
            db.session.commit()
            flash(f'{term} has been created.', 'success')
            return redirect(url_for('academics.index'))

    return render_template('edit-form.html', title=wbs.ACADEMIC_TERM.system_plural_capital, card_title=f'New {wbs.ACADEMIC_TERM.system_capital}', form=form)


@academics.route('/terms/edit/<term_id>', methods=['GET', 'POST'])
@admin_required
def edit_term(term_id):
    term = Term.query.filter_by(id=term_id).first()

    if not term:
        raise EntityNotFound(entity_name=wbs.ACADEMIC_TERM.system_capital, entity_id=term_id)

    form = TermForm(obj=term)

    if form.validate_on_submit():
        candidate = Term.query.filter((Term.start_date <= form.end_date.data) & (Term.end_date >= form.start_date.data)).first()

        if candidate and candidate != term:
            flash(f'A {wbs.ACADEMIC_TERM.system} within that date range already exists.')
        else:
            form.populate_obj(term)
            db.session.commit()
            flash(f'Changes to {wbs.ACADEMIC_TERM.system} #{term.id} have been made.', 'success')

    return render_template('edit-form.html', title=wbs.ACADEMIC_TERM.system_plural_capital, card_title=f'Editing {wbs.ACADEMIC_TERM.system_capital} #{term.id}: {term}', form=form)

whiteboard/views/auth.py
from datetime import datetime
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user, current_user
from werkzeug.security import check_password_hash, generate_password_hash
from whiteboard import settings as wbs
from whiteboard.forms import EditStudentForm, EditTeacherForm, LoginForm, RegistrationForm
from whiteboard.models import Student, Teacher, User, db
from whiteboard.views import admin_required, anonymous_required
from whiteboard.views.exceptions import EntityNotFound

auth = Blueprint('auth', __name__, template_folder='../templates/auth')


@auth.route('/register', methods=['GET', 'POST'])
@anonymous_required
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        if User.query.filter(User.username.ilike(form.username.data)).first():
            flash('This username is already in use.', 'error')
        elif User.query.filter(User.email.ilike(form.email.data)).first():
            flash('This email is already in use.', 'error')
        else:
            new_user = User(username=form.username.data.upper(), password=generate_password_hash(form.password.data), full_name=form.full_name.data, display_name=form.display_name.data, email=form.email.data.lower())
            db.session.add(new_user)
            db.session.flush()

            if form.is_teacher.data:
                new_teacher = Teacher(user_id=new_user.id)
                db.session.add(new_teacher)
            else:
                new_student = Student(user_id=new_user.id)
                db.session.add(new_student)

            db.session.commit()
            flash(f"{form.username.data}'s application has been sent for verification.", 'success')
            return redirect(url_for('root.index'))

    return render_template('register.html', form=form)


@auth.route('/login', methods=['GET', 'POST'])
@anonymous_required
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data.upper()).first()

        if user and check_password_hash(user.password, form.password.data):
            if user.is_active:
                login_user(user)
                return redirect(url_for('root.index'))
            else:
                flash('Your account application is currently being processed. For more information, please refer to a faculty or staff member.')
        else:
            flash('You have entered an invalid username or password.', 'error')

    return render_template('login.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been successfully logged out.', 'success')
    return redirect(url_for('root.index'))


@auth.route('/applicants', methods=['GET', 'POST'])
@admin_required
def applicants():
    applicants = User.query.filter_by(join_date=None)
    return render_template('applicants.html', applicants=applicants)


@auth.route('/applicants/<applicant_id>', methods=['POST'])
@admin_required
def admissions(applicant_id):
    applicant = User.query.filter_by(id=applicant_id).first()

    if not applicant or applicant.is_active:
        raise EntityNotFound(entity_name='Applicant', entity_id=applicant_id)

    if 'decision' in request.form:
        pass
    elif 'confirmation' in request.form:
        if request.form['confirmation'] == 'Accept':
            applicant.join_date = datetime.utcnow()
            db.session.commit()
            flash(f"{applicant.full_name}'s account with {wbs.CAMPUS_CARD.formal_name} {applicant.username} has been verified.", 'success')
        elif request.form['confirmation'] == 'Reject':
            db.session.delete(applicant)
            db.session.commit()
            flash(f"{applicant.full_name}'s application with {wbs.CAMPUS_CARD.formal_name} {applicant.username} has been deleted.", 'success')

        return redirect(url_for('auth.applicants'))
    else:
        flash('An unknown error has occurred', 'error')
        return redirect(url_for('auth.applicants'))

    return render_template('admissions.html', applicant=applicant)


@auth.route('/users')
@login_required
def users():
    active_users = User.query.filter(User.join_date != None)
    teachers = active_users.filter(User.teacher != None)
    students = active_users.filter(User.student != None)
    return render_template('users.html', teachers=teachers, students=students)


@auth.route('/users/<user_id>')
@login_required
def user_info(user_id):
    user = User.query.filter_by(id=user_id).first()

    if not user:
        raise EntityNotFound(entity_name=User.__name__, entity_id=user_id)

    return render_template('user.html', user=user)


@auth.route('/users/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    if current_user.is_teacher:
        form = EditTeacherForm(obj=current_user.teacher)

        if form.validate_on_submit():
            form.populate_obj(current_user.teacher)
            db.session.commit()
            flash('Your profile has been updated!', 'success')
    else:
        form = EditStudentForm(obj=current_user.student)

        if form.validate_on_submit():
            form.populate_obj(current_user.student)
            db.session.commit()
            flash('Your profile has been updated!', 'success')

    return render_template('edit-profile.html', title='Edit Profile', form=form)

whiteboard/templates/academics/academics.html
{% extends 'layout.html' %}

{% from 'macros.html' import action_links with context %}

{% block title %}Academics - {{ super() }}{% endblock %}

{% block content %}
    <section id="index">
        <header><h2>Index</h2></header>
        <nav>
            <ul>
                <li><a href="#departments">Departments</a></li>
                <li><a href="#majors">Majors</a></li>
                <li><a href="#majors">Courses</a></li>
                <li><a href="#terms">{{ config.ACADEMIC_TERM.system_plural_capital }}</a></li>
            </ul>
        </nav>
    </section>

    <section id="departments">
        <header>
            <h2>Departments</h2>
            {% call action_links(current_user.is_teacher) %}
                {{ nav_link(url_for('academics.new_department'), 'Add New Department', append_return_url=True) }}
            {% endcall %}
        </header>

        {% if departments %}
            {% for department in departments %}
                <section class="card">
                    <header>
                        <h3>{{ department }}</h3>
                        {% call action_links(current_user.is_teacher) %}
                            {{ nav_link(url_for('academics.edit_department', department_id=department.id), 'Edit', append_return_url=True) }}
                        {% endcall %}
                    </header>
                    <p>Chair: <strong class="emphasized">{{ department.chair }}</strong></p>
                    <p>Office: <strong class="emphasized">{{ department.office }}</strong></p>
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No departments listed.</em></p>
        {% endif %}
    </section>

    <section id="majors">
        <header>
            <h2>Majors</h2>
            {% call action_links(current_user.is_teacher) %}
                {{ nav_link(url_for('academics.new_major'), 'Add New Major', append_return_url=True) }}
            {% endcall %}
        </header>

        {% if majors %}
            {% for major in majors %}
                <section class="card">
                    <header>
                        <h3>{{ major }}</h3>
                        {% call action_links(current_user.is_teacher) %}
                            {{ nav_link(url_for('academics.edit_major', major_id=major.id), 'Edit', append_return_url=True) }}
                        {% endcall %}
                    </header>
                    {% if major.department %}
                        <p>Department: <strong class="emphasized">{{ major.department.name }}</strong></p>
                    {% endif %}
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No majors listed.</em></p>
        {% endif %}
    </section>

    <section id="courses">
        <header>
            <h2>Courses</h2>
            {% call action_links(current_user.is_teacher) %}
                {{ nav_link(url_for('academics.new_course'), 'Add New Course', append_return_url=True) }}
            {% endcall %}
        </header>

        {% if courses %}
            {% for course in courses %}
                <section class="card">
                    <header>
                        <h3>{{ course }}</h3>
                        {% call action_links(current_user.is_teacher) %}
                            {{ nav_link(url_for('academics.edit_course', course_id=course.id), 'Edit', append_return_url=True) }}
                        {% endcall %}
                    </header>
                    <p>Name: <strong class="emphasized">{{ course.name }}</strong></p>
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No courses listed.</em></p>
        {% endif %}
    </section>

    <section id="terms">
        <header>
            <h2>{{ config.ACADEMIC_TERM.system_plural_capital }}</h2>
            {% call action_links(current_user.is_teacher) %}
                {{ nav_link(url_for('academics.new_term'), 'Add New ' + config.ACADEMIC_TERM.system_capital, append_return_url=True) }}
            {% endcall %}
        </header>

        {% if terms %}
            {% for term in terms %}
                <section class="card">
                    <header>
                        <h3>{{ term }}</h3>
                        {% call action_links(current_user.is_teacher) %}
                            {{ nav_link(url_for('academics.edit_term', term_id=term.id), 'Edit', append_return_url=True) }}
                        {% endcall %}
                    </header>
                    <p>Start Date: <strong class="emphasized">{{ term.start_date }}</strong></p>
                    <p>End Date: <strong class="emphasized">{{ term.end_date }}</strong></p>
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No {{ config.ACADEMIC_TERM.system_plural }} listed.</em></p>
        {% endif %}
    </section>
{% endblock %}

whiteboard/templates/academics/admissions.html
{% extends 'applicants.html' %}

{% block title %}Admissions - {{ super() }}{% endblock %}

{% block content %}
    <section>
        <header><h2>Admissions</h2></header>
        <section class="applicant card">
            {{ application(applicant) }}

            <p class="emphasized"><em>Are you sure you want to <strong>{{ request.form.decision }}</strong> this applicant?</em></p>
            <form class="inlined" method="post">
                <div>
                    {{ get_csrf_token() }}
                    <input class="emphasized" type="submit" name="confirmation" value="{{ request.form.decision }}">
                    <input type="submit" name="confirmation" value="Cancel">
                </div>
            </form>
        </section>
    </section>
{% endblock %}

whiteboard/templates/academics/applicants.html
{% extends 'forms.html' %}

{% macro application(applicant) %}
    <header>
        <h3 {% if applicant.is_teacher %}class="emphasized"{% endif %}>{{ applicant.identity }} Applicant #{{ applicant.id }}</h3>
    </header>
    <table>
        <tr>
            <td>{{ config.CAMPUS_CARD.formal_name }}:</td>
            <td>{{ applicant.username }}</td>
        </tr>
        <tr>
            <td>Full Name:</td>
            <td>{{ applicant.full_name }}</td>
        </tr>
        {% if applicant.display_name %}
            <tr>
                <td>Display Name:</td>
                <td>{{ applicant.display_name }}</td>
            </tr>
        {% endif %}
        <tr>
            <td>Email Address:</td>
            <td>{{ applicant.email }}</td>
        </tr>
    </table>
{% endmacro %}

{% block title %}Applicants - {{ super() }}{% endblock %}

{% block style %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='applicants.css') }}">
{% endblock %}

{% block content %}
    <section>
        <header><h2>Applicants</h2></header>
        {% if applicants.count() > 0 %}
            {% for applicant in applicants %}
                <section class="applicant card">
                    {{ application(applicant) }}

                    <form class="inlined" action="{{ url_for('auth.admissions', applicant_id=applicant.id) }}" method="post">
                        <div>
                            {{ get_csrf_token() }}
                            <input class="emphasized" type="submit" name="decision" value="Accept">
                            <input type="submit" name="decision" value="Reject">
                        </div>
                    </form>
                </section>
            {% endfor %}
        {% else %}
            <p class="emphasized"><em>No applicants at this time.</em></p>
        {% endif %}
    </section>
{% endblock %}

whiteboard/templates/academics/division.html
{% extends 'forms.html' %}

{% from 'macros.html' import action_links, get_return_link with context %}

{% block title %}{{ title }} - {{ super() }}{% endblock %}

{% block content %}
    <section>
        <header><h2>{{ title }}</h2></header>
        {% call action_links('h3') %}
            {{ get_return_link() }}
        {% endcall %}

        <section class="card">
            <header><h3>{{ card_title }}</h3></header>
            {{ print_form(form=form, method='post') }}
        </section>
    </section>
{% endblock %}